custom.message=Hello from Config Server!
server.port=8083
spring.application.name=product-service
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
spring.datasource.url=jdbc:h2:mem:product_db
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.h2.console.enabled=true
